### ISSUE TITLE
UFO export: Consider dedicated script

### ISSUE THREAD

**Issue by madig** [eellak/gsoc2018-cantarell#1]
Hi!
You may be interested in https://github.com/googlei18n/glyphsLib/pull/361 -- I'm trying to upstream code we use internally to store font sources as UFOs and roundtrip to Glyphs only when needed. Glyphs metadata stays mostly intact. I'd be interested in feedback so I can finally merge this.

**Comment by grautesk** [comment]
Thanks for pointing me to this. Exceeds my level of knowledge; it’s a command line tool, right? I pip installed fonttools, defcon, MutatorMath, glyphsLib — and how do I run it then?

**Comment by madig** [comment]
Yes, it's a command line tool. The code didn't land in glyphsLib yet, I recommend you uninstall what you installed (unless you need it for something else) and do this:
```
python3 -m venv venv
. venv/bin/activate
pip install git+https://github.com/madig/glyphsLib.git@glyphs-ufo-convert-scripts#egg=glyphsLib
glyphs2ufo Cantarell.glyphs
ufo2glyphs Cantarell.designspace
```
This will create a new virtual environment and activates it so you don't pollute your Python installation with development code. It then installs my code, you can then use the `glyphs2ufo` and `ufo2glyphs` scripts to convert back and forth. You might see random changes when you go back and forth. Unfortunately, the roundtripping isn't 100% lossless...

**Comment by grautesk** [comment]
Thanks, installed your code. I tried to test it with a copy on my desktop:
`glyphs2ufo ~/Desktop/Cantarell.glyphs`
Pip installed 'ufonormalizer' because I received a ModuleNotFoundError-message and it only created Cantarell-Light.ufo. Now I get the three masters as UFO and a DESIGNSPACE, **but:** Only Cantarell-Regular.ufo opens in Robofont, for the Light and Bold I receive the error massage “[…] could not be opened. The file isn’t in the correct format.” Tried it with your [forked Cantarell](https://github.com/madig/cantarell-fonts/blob/master/src/Cantarell.glyphs), just to check. None of the UFOs created from this file open in Robofont.

I can open all UFOs without error message in Glyphs 1. Glyphs 2.5 tells me it’s a file from an older version though it seems to work (like a GLYPHS-file from v1 opened in v2.5).

**Comment by madig** [comment]
Are you on Robofont 3? The script primarily generates UFO v3.

**Comment by grautesk** [comment]
Student licenses haven’t been upgraded yet, but I installed Robofont 3 and it works. I’ll use it for future exports and give feedback if I run into any issues. Thank you very much!
